version: "3.8"

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sheep
    ports:
      - "5432:5432"